language: node_js
matrix:
    fast_finish: true
node_js:
    - 10
notifications:
    email: false
before_install:
    - npm install --global flow-bin
    - npm install
install:
    - npm run test:full
